### ISSUE TITLE
Make list of Accessories show up on Contract

### ISSUE THREAD

**Issue by tilllt** [zhdk/leihs#8]
As a reminder for our students we would like to insert the accessory lists for an item show up on the contract. When they are packing up stuff to return it, they could check their contracts and see what is missing.

Right now we need to have to Browser Tabs open and manually copy over the accessory list from the model view to the contract notice which is kind of a hassle.

Additionally it would be great if this was optional, so you could select "Include Assessory List?" for each item.

**Comment by psy-q** [comment]
This was done in 3.30.0.
