### ISSUE TITLE
Be able to influence how inventory codes are constructed

### ISSUE THREAD

**Issue by psy-q** [zhdk/leihs#80]
The old system looked for the highest plain number in all existing inventory codes. e.g. if the following existed:

ABC123
BBB001
XZY129

Then the next generated inventory code in inventory pool "ABC" would be "ABC130". leihs 3.0 fills up any empty inventory code space instead of going for the highest possible number. Could it be changed so there is an option to use either the lowest free or the highest consecutive number?

**Comment by sellittf** [comment]
Currently there is no option to influence the suggested inventory code, but we can plan it as new feature.

Here the code:
https://github.com/zhdk/leihs/blob/master/app/models/item.rb#L317
and the helpers:
https://github.com/zhdk/leihs/blob/master/app/models/item.rb#L310
https://github.com/zhdk/leihs/blob/master/app/models/item.rb#L357

**Comment by psy-q** [comment]
The new item creation page has three buttons that can be used to select the desired behavior.
