### ISSUE TITLE
Creating New Category/Inventory Pool doesn't let current users access

### ISSUE THREAD

**Issue by mforbes620** [zhdk/leihs#95]
Hey everyone-

So this is a bit of an oddity. We are using LDAP for authentication. As it stands, if I create a new category with new models & items, the students who have previously logged in do not have access to that new category. Is there a way to give everyone access to a new Inventory Pool all at once?

I would go through and edit each user's account to give them access, but I have almost 500 student accounts and that would take a near lifetime.

We are currently running Leihs 3.8.0

Thanks for all your help!

**Comment by sellittf** [comment]
Hi mforbes620

Currently there isn't any way to bulk assign an access right to all users, something like that is not even planned yet.

Instead, on login for each user, assigning access right to a new inventory pool (marked with automatic access) makes sense. We will consider this improvement on future releases.

The only way now you can give access to all users to the new inventory pool, is through the console.
These are the commands to execute on the server:

```
$ cd {leihs root directory}
$ RAILS_ENV=production bundle exec rails console
```

```
> InventoryPool.where(automatic_access: true).each {|ip| User.all.each {|user| user.access_rights.create_with(role: :customer, inventory_pool: ip).find_or_create_by(inventory_pool_id: ip) }}
```

Done, now all the users receive access to the new inventory pools (the ones marked with automatic access)

Best regards
Franco

**Comment by psy-q** [comment]
3.31.0 will automatically give existing users access to new inventory pools if they are created with "automatic access" enabled.
