### ISSUE TITLE
Upgrade Problem 2.9.14 -> current

### ISSUE THREAD

**Issue by wolfgang-reutz** [zhdk/leihs#96]
Hi all,

i wanted to update our 2.9.14 instance of Leihs to the newest Version. I did it at the beginning of the year on my vagrant test machine and got it sucessfulle to 3.9 with steps 2.9.14 -> 3.0 -> 3.5 -> 3.9

Now i wanted to do it on the production server and i'm stuck at the step from 3.4 (upgraded sucessfully from 3.0 to 3.4) to 3.5 😔

i get an error that some ruby gem is missing, but i ran bundle install multiple times with no luck. So the migration to 3.5 fails alll the time.

if i recall it correctly it's the Gem acts-as-dag causing the problems.

can someone confirm this?
is there a fix?

i have zero knowledge in Ruby 😕

cheers, Wolfgang

Wolfgang Reutz
Webapplication Developer
University of Applied Sciences Vorarlberg, Austria

**Comment by psy-q** [comment]
What is the exact error message, could you please paste the relevant bits of the console log? 

Does the production server have git installed and can it connect to the outside world using HTTPS (port TCP 443)? I'm asking because the particular version of acts-as-dag used in leihs 3.5 is the [3.0.0 fork by jheiss](https://github.com/jheiss/acts-as-dag). If the server can't get to GitHub, it would produce an error.

**Comment by wolfgang-reutz** [comment]
the correct error is as following:

```bash
$ RAILS_ENV=production bundle exec rake db:migrate
Could not find acts-as-dag-3.0.0 in any of the sources
Run `bundle install` to install missing gems.
```

connecting to github on HTTPS using `lynx https://www.github.com/` did work.

**Comment by psy-q** [comment]
When you run `bundle install`, is there also an error?

**Comment by wolfgang-reutz** [comment]
no, that's the odd thing 😕

i run bundle install, i see acts-as-dag in the list of installed bundles, but still get the error of the missing bundle ...

**Comment by psy-q** [comment]
Could you try deleting `vendor/bundle` and running bundle install again? `vendor/bundle` is the default location for gems, we usually link it to some shared directory on our produciton servers so you may have to delete the contents of `shared/vendor` (not the `shared/vendor` dir) instead depending on how leihs is installed.

If I remember correctly, there were some bugs in older versions of the RubyGems system concerning installation of gems directly from GitHub, in some such cases deleting the bundle dir and restarting helps.

If this doesn't help, perhaps the version of RubyGems on your server has some other issues, but let's go one at a time, we can still upgrade RubyGems later.

**Comment by wolfgang-reutz** [comment]
deleting vendor/bundle did not work 😕

```bash
leihs@leihs:~/leihs$ bundle install
Fetching gem metadata from http://rubygems.org/.........
Fetching version metadata from http://rubygems.org/...
Fetching dependency metadata from http://rubygems.org/..
Fetching https://github.com/jheiss/acts-as-dag.git
Fetching https://github.com/bradphelan/jasminerice.git
Fetching https://github.com/spape/jsrender-rails.git
Installing rake 10.2.2
Installing i18n 0.6.9
Using minitest 4.7.5
Installing multi_json 1.9.2
Installing atomic 1.1.16 with native extensions
Installing thread_safe 0.3.1
Installing tzinfo 0.3.39
Installing activesupport 4.0.4
Installing builder 3.1.4
Installing erubis 2.7.0
Installing rack 1.5.2
Installing rack-test 0.6.2
Installing actionpack 4.0.4
Installing mime-types 1.25.1
Installing polyglot 0.3.4
Installing treetop 1.4.15
Installing mail 2.5.4
Installing actionmailer 4.0.4
Installing active_hash 1.3.0
Installing activemodel 4.0.4
Installing activerecord-deprecated_finders 1.0.3
Installing arel 4.0.2
Installing activerecord 4.0.4
Using acts-as-dag 3.0.0 from https://github.com/jheiss/acts-as-dag.git (at rails4)
Installing addressable 2.3.6
Installing barby 0.5.1
Installing mini_portile 0.5.3
Installing nokogiri 1.6.1 with native extensions
Installing xpath 2.0.0
Installing capybara 2.2.1
Installing launchy 2.4.2
Installing capybara-screenshot 0.3.17
Installing timers 1.1.0
Installing celluloid 0.15.2
Installing nio4r 1.0.0 with native extensions
Installing celluloid-io 0.15.0
Installing ffi 1.9.3 with native extensions
Installing childprocess 0.5.2
Installing chunky_png 1.3.0
Installing climate_control 0.0.3
Installing cliver 0.3.2
Installing cocaine 0.5.4
Installing coderay 1.1.0
Installing coffee-script-source 1.7.0
Installing execjs 2.0.2
Installing coffee-script 2.2.0
Installing haml 3.1.8
Installing coffee-filter 0.1.3
Installing thor 0.19.1
Installing railties 4.0.4
Installing coffee-rails 4.0.1
Installing fssm 0.2.10
Installing sass 3.2.18
Installing compass 0.12.4
Installing hike 1.2.3
Installing tilt 1.4.1
Installing sprockets 2.11.0
Installing compass-rails 1.1.7
Installing diff-lcs 1.2.5
Installing gherkin 2.12.2 with native extensions
Installing multi_test 0.1.1
Installing cucumber 1.3.14
Using bundler 1.10.6
Installing sprockets-rails 2.0.1
Installing rails 4.0.4
Installing cucumber-rails 1.4.0
Installing database_cleaner 1.2.0
Installing docile 1.1.3
Installing factory_girl 4.4.0
Installing factory_girl_rails 4.4.1
Installing faker 1.3.0
Installing fast_gettext 0.8.1
Installing font-awesome-rails 3.2.1.3
Installing formatador 0.2.4
Installing geocoder 1.1.9
Installing gettext_i18n_rails 1.0.3
Installing rb-fsevent 0.9.4
Installing rb-inotify 0.9.3
Installing listen 2.7.1
Installing lumberjack 1.0.5
Installing method_source 0.8.2
Installing slop 3.5.0
Installing pry 0.9.12.6
Installing guard 2.6.0
Installing guard-jasmine 1.19.1
Installing haml_assets 0.2.2
Using jasminerice 0.1.0 from https://github.com/bradphelan/jasminerice.git (at master)
Installing jquery-rails 2.1.3
Installing jquery-tmpl-rails 1.1.0
Using json 1.8.1
Using jsrender-rails 1.2 from https://github.com/spape/jsrender-rails.git (at own_template_prefix)
Installing open4 1.0.1
Installing ladle 0.2.0
Installing libv8 3.16.14.3
Installing subexec 0.2.3
Installing mini_magick 3.7.0
Installing mysql2 0.3.15 with native extensions
Installing net-ldap 0.5.1
Installing newrelic_rpm 3.7.3.204
Installing paperclip 3.5.4
Installing phantomjs 1.9.7.0
Installing websocket-driver 0.3.2 with native extensions
Installing poltergeist 1.5.0
Installing protected_attributes 1.0.7
Installing pry-rails 0.3.2
Installing rack_session_access 0.1.1
Installing rails_autolink 1.1.5
Installing redcarpet 3.1.1 with native extensions
Installing ref 1.0.5
Installing stream 0.5
Installing rgl 0.4.0
Installing rspec-core 2.14.8
Installing rspec-expectations 2.14.5
Installing rspec-mocks 2.14.6
Installing rspec 2.14.1
Installing rspec-rails 2.14.2
Installing sexp_processor 4.4.3
Installing ruby_parser 3.5.0
Installing rubyzip 1.1.2
Installing sass-rails 4.0.2
Installing websocket 1.0.7
Installing selenium-webdriver 2.41.0
Installing simplecov-html 0.8.0
Installing simplecov 0.8.2
Installing therubyracer 0.12.1 with native extensions
Installing timecop 0.7.1
Installing uglifier 2.5.0
Installing underscore-rails 1.6.0
Installing uuidtools 2.1.4
Installing will_paginate 3.0.5
Installing yard 0.8.7.4
Bundle complete! 70 Gemfile dependencies, 131 gems now installed.
Gems in the groups cucumber and development were not installed.
Bundled gems are installed into ./vendor/bundle.
Post-install message from barby:

*** NEW REQUIRE POLICY ***"
Barby no longer require all barcode symbologies by default. You'll have
to require the ones you need. For example, if you need EAN-13,
require 'barby/barcode/ean_13'; For a full list of symbologies and their
filenames, see README.
***

Post-install message from newrelic_rpm:
# New Relic Ruby Agent Release Notes #

## v3.7.3 ##

* Obfuscation for PostgreSQL explain plans

  Fixes an agent bug with PostgreSQL where parameters from the original query
  could appear in explain plans sent to New Relic servers, even when SQL
  obfuscation was enabled. Parameters from the query are now masked in explain
  plans prior to transmission when transaction_tracer.record_sql is set to
  'obfuscated' (the default setting).

  For more information, see:
  https://docs.newrelic.com/docs/traces/security-for-postgresql-explain-plans

* More accurate categorization of SQL statements

  Some SQL SELECT statements that were previously being mis-categorized as
  'SQL - OTHER' will now correctly be tagged as 'SQL - SELECT'. This
  particularly affected ActiveRecord users using PostgreSQL.

* More reliable Typhoeus instrumentation

  Fixed an issue where an exception raised from a user-specified on_complete
  block would cause our Typhoeus instrumentation to fail to record the request.

* Fix for Puma 2.8.0 cluster mode (3.7.3.204)

  Puma's 2.8.0 release renamed a hook New Relic used to support Puma's cluster
  mode.  This resulted in missing data for users running Puma. Thanks Benjamin
  Kudria for the fix!

* Fix for deployment command bug (3.7.3.204)

  Problems with file loading order could result in `newrelic deployments`
  failing with an unrecognized command error. This has been fixed.

    See https://github.com/newrelic/rpm/blob/master/CHANGELOG for a full list of
    changes.
leihs@leihs:~/leihs$ RAILS_ENV=production bundle exec rake db:migrate
Could not find acts-as-dag-3.0.0 in any of the sources
Run `bundle install` to install missing gems.
leihs@leihs:~/leihs$ 
```

**Comment by psy-q** [comment]
I haven't seen Rubygems behave like that before :( What are the versions of Rubygems amd Ruby in this case? `rubygems -v` should say something. I will try to reppicate the problem with the exact same versions to see if a newer Rubygems might help. Also, is there RVM, rbenv or some other Ruby versiin manager?

**Comment by wolfgang-reutz** [comment]
here are the versions i use:

```bash
leihs@leihs:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty
leihs@leihs:~$ ruby --version
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux]
leihs@leihs:~$ rvm --version
rvm 1.26.11 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
leihs@leihs:~$ gem --version
2.4.3
```

**Comment by psy-q** [comment]
Ah, for some reason I'm getting a proper error message with that combination:

```
The gemspec at /home/leihs/test/shared/bundle/ruby/2.1.0/bundler/gems/acts-as-dag-d7cdd8bde5d5/acts-as-dag.gemspec is not valid. The validation error was 'duplicate dependency on activerecord (>= 0), (~> 3.2.12) use:
    add_runtime_dependency 'activerecord', '>= 0', '~> 3.2.12'
```

It appears that Rubygems is too new, the gemspec defintions have changed over time and the version of acts-as-dag we used to use clashes with modern versions of Rubygems. I will fiddle until I find an old enough version of Rubygems to work. This is unfortunately something that can happen in the Rails world, I don't know of a good way to combat this. I will probably have to give instructions for the exact Rubygems versions to use for each upgrade step.

**Comment by psy-q** [comment]
Please try with Rubygems 2.0.14:
```
gem update --system 2.0.14
```
I've managed to upgrade from 3.4.0 to 3.5.0 with this. Perform the migration to leihs 3.5.0, later on, when moving ahead to leihs 3.14.0 you can again upgrade to the latest Rubygems.

**Comment by wolfgang-reutz** [comment]
sorry to bother you again, i upgraded to 3.5.0 and now to 3.14.0

when i run ``

i get no response, no error but normally i get a message that migrate did something.

now i have another problem: when i log in (which works with shibboleth 😉 by doing my modification as it's pre 3.17.0) and try to access "database check" i get an error:

```
Started GET "/admin/database_indexes" for 193.170.2.242 at 2015-08-31 21:20:34 +0200
Processing by Admin::DatabaseController#indexes as HTML
Mysql2::Error: Table 'leihs_production.audits' doesn't exist: SHOW KEYS FROM `audits`
Completed 500 Internal Server Error in 10ms

ActiveRecord::StatementInvalid (Mysql2::Error: Table 'leihs_production.audits' doesn't exist: SHOW KEYS FROM `audits`):
  app/controllers/admin/database_controller.rb:89:in `block in indexes'
  app/controllers/admin/database_controller.rb:88:in `each'
  app/controllers/admin/database_controller.rb:88:in `partition'
  app/controllers/admin/database_controller.rb:88:in `indexes'
```

shouldn't this table be created by the migration script?

and a note: i have to stay on rubygems 2.0.14 for version 3.14.0 of leihs as well, using the newest version failed again with acts-as-dag error.

**Comment by psy-q** [comment]
Thanks for the information about Rubygems 2.0.14, I've added an explanation to the upgrade section in the admin guide.

The error with the audits is very strange, audits were not officially added until leihs 3.28.1 so database consistency check should not even look at the audit tables. In `app/controllers/admin/database_controller.rb` you should see that on lines 31 to 35, checking of the audit tables is commented out.

How are you moving between the different versions of leihs during the upgrade? If you're using git and checking out each tag in detached HEAD mode, you could use e.g. `git reset --hard 3.14.0` to make sure that no cruft from any newer version is hanging around if you need to move back and forth between versions.

Or safer yet, you might want to unpack each leihs version in its own separate directory from the tarballs on the [releases page](https://github.com/zhdk/leihs/releases). That's how I usually do the upgrade sequence when I do upgrades for customers.

Do comment if that doesn't help :) I just went through the sequence again and the consistency check worked.

**Comment by wolfgang-reutz** [comment]
ok, that was my mistake, i did a `git reset --hard` and didn't know that it resets to another version.

after using git reset --hard 3.14.0 it worked, consistency check did say "all correct" and now i'm on 3.14.0

now i have another problem:

i checked out 3.30.1 and ran migrate, then i got an error that "mail_templates" table could not be found and migrate was cancelled.

so i think a direkt upgrade from 3.14.0 to 3.30.1 (or 3.30.0) is not possible?

**Comment by psy-q** [comment]
Ah, missed one version! Apparently it's necessary to go to 3.23.0 before continuing to 3.30.1. I change the guide to reflect that.

**Comment by wolfgang-reutz** [comment]
Thank you so much for all your help!

I'm now on 3.30.1 and it seems everything is working. I will test it now over the weekend and instruct my fellow leihs managers and then we will switch our production system from 2.9.14 to 3.30.1 ;-)

**Comment by psy-q** [comment]
Whew, great! I hope everyone's happy once it goes into production!
