### ISSUE TITLE
shibboleth login does not create new users

### ISSUE THREAD

**Issue by wolfgang-reutz** [zhdk/leihs#99]
right now i was informed that the shibboleth login is not working for new users.
i have to debug it further, but i think the problem is this:

in shibboleth authentication controller:
    if request.env[@config['unique_id_field']].blank?
      redirect_to root_path
    else
      self.current_user = create_or_update_user
      redirect_to root_path
    end

the login for existing users works, that's why i did not find this error earlier.
but when a new user is sucessfully authorized by shibboleth he gets here and as our shibboleth sets the env\['uid'\] (uid = unique_id_field), he gets directly redirected to the root path and no user is created!

maybe i'm wrong, but this is not correct?
is it save to do a create_or_update_user on each login?
or is there another if statement to use to decide if a user is new or existing?
as i see it tho choose based on the fact that shibboleth sets an environment field is not enough

what do you think?

cheers, wolfgang

**Comment by psy-q** [comment]
Redirecting to the root path should be okay, since the [application controller takes care to redirect](https://github.com/zhdk/leihs/blob/master/app/controllers/application_controller.rb#L6) the user to the right place depending on their permissions.

But what's worrying is that it appears to take the wrong path there. I don't know if perhaps something changed about handling the env in newer Rails versions. @sellittf , do you know what this could be, perhaps?

Our tests do test up to the login and the users are created correctly when `@config['unique_id_field']` is set. But they do not verify anything beyond that (e.g. if the correct redirection is used).

**Comment by wolfgang-reutz** [comment]
i guess the problem is more like:
if request.env[@config['unique_id_field']].blank?
redirect_to root_path
else
self.current_user = create_or_update_user
redirect_to root_path
end

as i understand it: create_or_update_user is only called when 'uid' is not in the env, which is set by shibboleth SP, which in our case is always set, as the user is authenticated sucessfully by shibboleth.

whats missing is that the shibboleth controller should check against the database if the user already exists, but i can't see that as you take the presence of the uid field for this decision?

so create_or_update will never be called in any case ... or am i wrong?

**Comment by psy-q** [comment]
Well, since you say that the unique_id_field is *always* set, that would mean that create_or_update_user is always called. The decision whether to create or update a user is taken in create_or_update_user, if the user is already there, their data is updated with some fields from Shibboleth, if not, the user is created. In both cases the user is logged in.

If you want to poke around that, you could try to just replace the condition with an unconditional create:

```ruby
  def login
    super
    # This point should only be reached after a successful login from Shibboleth.
    # Shibboleth handles all error management, so we don't need to worry about any
    # of that.
    self.current_user = create_or_update_user
    redirect_to root_path
  end
```
There isn't a reason to hit the database to look for the user if `request.env[@config['unique_id_field']]` is absolutely guaranteed to be set, because create_or_update_user does the check as well. It first searches for a user (`User.where`) and if none is found with the given unique ID, creates a new one (`|| User.new`).

**Comment by wolfgang-reutz** [comment]
ok then i misunderstood the code 😉 i'm no ruby programmer ...

create_or_update_user is called i guess, but the problem remains: there are NO NEW users created! this is a big problem for us as the leihs 3.x is now running in production and on 2.9.14 this worked and unfortunately we didn't find this bug earlier 😕

as i don't know ruby on rails: how can i debug? i added 

```ruby
    logger = Rails.logger
    logger.error env
```

to app/controllers/authenticator/ShibbolethAuthenticationController.rb but i don't see the log message in the production.log

do i have to restart apache (using phusion) every time a do a change to the source files?

i have to find a quick fix as right now only "old" users can log in, but no "new" users get access to the system as their users are not created in the DB ...

**Comment by psy-q** [comment]
Oh, good work logging that! Try logging: `user.errors.full_messages` to see if maybe the save was attempted but not successful. I think the newer authentication adapters (the LDAP one for example) have much better error checking so they would actually let the user know what went wrong, but for the Shibboleth one this can't be implemented the same way at all due to the way it works :(

**Comment by wolfgang-reutz** [comment]
thanks a lot! this was the missing clue i needed.

after logging the error message which was "lastname can not be empty!", i found the error which was the wrong name of the field in our LDAP. We use `sn` for the lastname and not `surname`.

i changed the `app/controllers/authenticator/shibboleth_authentication_controller.rb` a bit to support configurable fieldnames for shibboleth depending on your LDAP:

```ruby
# In order to use this Shibboleth authenticator, you must put the entire
# leihs instance behind a shibboleth "secure" location:
#
# <Location />
#    AuthType shibboleth
#    ShibRequireSession On
#    require valid-user
#  </Location>
#
# You must also have a working service provider (SP) for this instance.

class Authenticator::ShibbolethAuthenticationController < Authenticator::AuthenticatorController

  before_filter :load_config

  def load_config

    begin
      if (defined?(Setting::SHIBBOLETH_CONFIG) and not Setting::SHIBBOLETH_CONFIG.blank?)
        shibboleth_config = YAML::load_file(Setting::SHIBBOLETH_CONFIG)
      else
        shibboleth_config = YAML::load_file(File.join(Rails.root, 'config', 'shibboleth.yml'))
      end

      if shibboleth_config[Rails.env].nil?
        raise "The configuration section for the environment '#{Rails.env}' is missing in your shibboleth config file."
      else
        @config = shibboleth_config[Rails.env]
        if @config['admin_uids']
          @super_users = @config['admin_uids']
        end
      end
    rescue Exception => e
      raise "Could not load Shibboleth configuration file: #{e}"
    end
  end

  layout 'layouts/manage/general'

  def login_form_path
    '/authenticator/shibboleth/login'
  end

  def login
    super
    # This point should only be reached after a successful login from Shibboleth.
    # Shibboleth handles all error management, so we don't need to worry about any
    # of that.
    if request.env[@config['unique_id_field']].blank?
      redirect_to root_path
    else
      self.current_user = create_or_update_user
      redirect_to root_path
    end
  end  

  def create_or_update_user

    # request.env after Shibboleth authentication looks like this:
#    "uid"=>"e10262@zhdk.ch", 
#    "homeOrganizationType"=>"uas", 
#    "givenName"=>"Ramon", 
#    "Shib-AuthnContext-Class"=>"urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport", 
#    "Shib-Identity-Provider"=>"https://aai-logon.zhdk.ch/idp/shibboleth", 
#    "Shib-InetOrgPerson-givenName"=>"Ramon", 
#    "Shib-Authentication-Method"=>"urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport", 
#    "mail"=>"ramon.cahenzli@zhdk.ch", 
#    "Shib-SwissEP-HomeOrganization"=>"zhdk.ch", 
#    "Shib-Application-ID"=>"leihs2shib", 
#    "Shib-Person-surname"=>"Cahenzli", 
#    "Shib-EP-Affiliation"=>"faculty;staff;member", 
#    "Shib-Authentication-Instant"=>"2010-09-28T07:03:59.738Z", 
#    "Shib-SwissEP-UniqueID"=>"e10262@zhdk.ch", 
#    "Shib-SwissEP-HomeOrganizationType"=>"uas", 
#    "Shib-InetOrgPerson-mail"=>"ramon.cahenzli@zhdk.ch", 
#    "Shib-Session-ID"=>"_22d5e2f708f663eae29d2afeae08dfff", 
#    "surname"=>"Cahenzli", "homeOrganization"=>"zhdk.ch", 
#    "affiliation"=>"faculty;staff;member" 

    uid = request.env[@config['unique_id_field']]
    email = request.env[@config['mail_field']]
    user = User.where(unique_id: uid).first || User.where(email: email).first || User.new
    user.unique_id = uid
    user.login = uid
    user.email = email
    user.firstname = "#{request.env[@config['firstname_field']]}"
    user.lastname = "#{request.env[@config['lastname_field']]}"
    user.authentication_system = AuthenticationSystem.where(class_name: 'ShibbolethAuthentication').first
    user.save
    unless user.errors.full_messages.blank?
      logger = Rails.logger
      logger.error user.errors.full_messages
    end

    if @super_users.include?(user.unique_id)
      user.access_rights.create(role: :admin, inventory_pool: nil)
    end
    user
  end

end
```

and i changed `config/shibboleth.yml.example`:

```yaml
production:
  unique_id_field: uid
  firstname_field: givenName
  lastname_field: surname
  mail_field: mail
  admin_uids:
    - hewey
    - dewey
    - louie
```

If this code is ok for you, could you please add it to a future release?

This way it would be possible for us (and others using shibboleth) to configure the fieldnames in one place in the shibboleth config file.

but i found another glitch:

some of our users have only 2 characters, if the user is already existent in leihs (or maybe if it is defined as a super user) it works, but throws an error message at each login with my code above. but even with this error message i can sucessfully log in.

the only problem is with "new" users with only 2 characters - creation of these users fails and returns them silently to the login page - no user is created in this case.

cheers, wolfgang

**Comment by psy-q** [comment]
Looks good! I will try to bang your changes into roughly the same shape as the LDAP login adapter, so that the adapter raises errors if it's not sufficiently configured (e.g. if a firstname or lastname section is missing from the config). This proved pretty useful for that adapter. Thanks!

**Comment by psy-q** [comment]
I've ported your changes to our controller and wrote tests for them, validating the config file and raising exceptions if required fields/configurations are not found. It's all [in a separate branch](https://github.com/zhdk/leihs/tree/rca/expand_shibboleth_config) at the moment, but I'm hoping we can merge it into 3.31.0.

Thanks for the debugging and the work :)
